version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/SolTradeAI/api
    steps:
      - checkout:
          path: ~/SolTradeAI
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - package.json
            - package-lock.json
            - docker-compose.yml
            - ecosystem-prod.config.js
            - ecosystem-dev.config.js

  deploy-prod:
    docker:
      - image: cimg/base:stable
    working_directory: ~/SolTradeAI/api
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Adding DigitalOcean Host to Known Hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh root@$DROPLET_IP 'mkdir -p /var/www/SolTradeAI-prod'
            for var in NODE_ENV PORT WEBSOCKET_PORT BASE_URL MAIL_FROM_ADDRESS MAIL_FROM_NAME \
                      OAUTH_CLIENT_ID OAUTH_CLIENT_SECRET OAUTH_REDIRECT_URI OAUTH_REFRESH_TOKEN \
                      MONGO_USER MONGO_PASSWORD MONGO_HOST MONGO_PORT MONGO_DATABASE MONGO_URI \
                      S3_ENDPOINT S3_PORT S3_USE_SSL S3_AVATAR_BUCKET S3_BACKGROUND_BUCKET \
                      S3_BUCKET S3_ACCESS_KEY S3_SECRET_KEY JWT_SECRET JWT_ISSUER JWT_VALID_MINS \
                      SENTRY_DNS OPENAI_API_KEY DEEPSEEK_API_KEY OPENAI_MODEL STORK_API_KEY \
                      RPC_URL PRIVATE_KEY ZERO_EX_API_KEY REDIS_PASSWORD REDIS_HOST REDIS_PORT \
                      CURVANCE_UNIVERSAL_BALANCE_ADDRESS CURVANCE_ETOKEN_USDC_ADDRESS \
                      CURVANCE_ETOKEN_WBTC_ADDRESS CURVANCE_ETOKEN_AUSD_ADDRESS \
                      CURVANCE_PTOKEN_LUSD_ADDRESS CURVANCE_PTOKEN_USDC_ADDRESS \
                      CURVANCE_PTOKEN_WBTC_ADDRESS WALLET_ADDRESS BULLBOARD_USER BULLBOARD_PASS \
                      BONDING_CONTRACT_ADDRESS FAUCET_CONTRACT_ADDRESS FAUCET_ROLE_PRIVATE_KEY \
                      DISCORD_CLIENT_ID DISCORD_CLIENT_SECRET DISCORD_REDIRECT_URI DISCORD_SERVER_ID FAUCET_URL \
                      TERMINAL_RATE_LIMIT_DURATION_IN_SECONDS ENCRYPTION_KEY \
                      TWITTER_CLIENT_ID TWITTER_CLIENT_SECRET TWITTER_REDIRECT_URI TWITTER_ACCOUNT_HANDLER; do

              prefixed_var="PROD_${var}"
              val="${!prefixed_var}"

              if [ -n "$val" ]; then
                echo "${var}=${val}" >> .env
              fi
            done
            tar -czf deploy.tar.gz build package.json ecosystem-prod.config.js docker-compose.yml .env
            scp deploy.tar.gz root@$DROPLET_IP:/var/www/SolTradeAI-prod/

            ssh root@$DROPLET_IP 'cd /var/www/SolTradeAI-prod && \
            tar -xzf deploy.tar.gz && \
            rm deploy.tar.gz && \

            source ~/.profile && \
            source ~/.bashrc && \
            export NVM_DIR="$HOME/.nvm" && \
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
            npm install -g pm2 && \
            pm2 delete SolTradeAI-prod || true && \
            pm2 start ecosystem-prod.config.js && \
            pm2 save'

  deploy-dev:
    docker:
      - image: cimg/base:stable
    working_directory: ~/SolTradeAI/api
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Adding DigitalOcean Host to Known Hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
      - run:
          name: Deploy to DigitalOcean
          command: |
            ssh root@$DROPLET_IP 'mkdir -p /var/www/SolTradeAI-dev'
            for var in NODE_ENV PORT WEBSOCKET_PORT BASE_URL MAIL_FROM_ADDRESS MAIL_FROM_NAME \
                      OAUTH_CLIENT_ID OAUTH_CLIENT_SECRET OAUTH_REDIRECT_URI OAUTH_REFRESH_TOKEN \
                      MONGO_USER MONGO_PASSWORD MONGO_HOST MONGO_PORT MONGO_DATABASE MONGO_URI \
                      S3_ENDPOINT S3_PORT S3_USE_SSL S3_AVATAR_BUCKET S3_BACKGROUND_BUCKET \
                      S3_BUCKET S3_ACCESS_KEY S3_SECRET_KEY JWT_SECRET JWT_ISSUER JWT_VALID_MINS \
                      SENTRY_DNS OPENAI_API_KEY DEEPSEEK_API_KEY OPENAI_MODEL STORK_API_KEY \
                      RPC_URL PRIVATE_KEY ZERO_EX_API_KEY REDIS_PASSWORD REDIS_HOST REDIS_PORT \
                      CURVANCE_UNIVERSAL_BALANCE_ADDRESS CURVANCE_ETOKEN_USDC_ADDRESS \
                      CURVANCE_ETOKEN_WBTC_ADDRESS CURVANCE_ETOKEN_AUSD_ADDRESS \
                      CURVANCE_PTOKEN_LUSD_ADDRESS CURVANCE_PTOKEN_USDC_ADDRESS \
                      CURVANCE_PTOKEN_WBTC_ADDRESS WALLET_ADDRESS BULLBOARD_USER BULLBOARD_PASS \
                      BONDING_CONTRACT_ADDRESS FAUCET_CONTRACT_ADDRESS FAUCET_ROLE_PRIVATE_KEY \
                      DISCORD_CLIENT_ID DISCORD_CLIENT_SECRET DISCORD_REDIRECT_URI DISCORD_SERVER_ID FAUCET_URL \
                      TERMINAL_RATE_LIMIT_DURATION_IN_SECONDS ENCRYPTION_KEY \
                      TWITTER_CLIENT_ID TWITTER_CLIENT_SECRET TWITTER_REDIRECT_URI TWITTER_ACCOUNT_HANDLER; do

              prefixed_var="DEV_${var}"
              val="${!prefixed_var}"

              if [ -n "$val" ]; then
                echo "${var}=${val}" >> .env
              fi
            done
            tar -czf deploy.tar.gz build package.json ecosystem-dev.config.js docker-compose.yml .env
            scp deploy.tar.gz root@$DROPLET_IP:/var/www/SolTradeAI-dev/

            ssh root@$DROPLET_IP 'cd /var/www/SolTradeAI-dev && \
            tar -xzf deploy.tar.gz && \
            rm deploy.tar.gz && \

            source ~/.profile && \
            source ~/.bashrc && \
            export NVM_DIR="$HOME/.nvm" && \
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
            npm install -g pm2 && \
            pm2 delete SolTradeAI-dev || true && \
            pm2 start ecosystem-dev.config.js && \
            pm2 save'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                # - develop-deploy
                - main
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only:
                # - develop-deploy
                # - develop-deploy
                - develop
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: main

